from __future__ import annotations

import json
from pathlib import Path
from typing import Any


OUTPUT_ROOT = Path("data/cross_api_test_cases")


CAPABILITY = {
    "route": True,
    "plan": True,
    "execute": True,
    "present": True,
    "clarify": False,
    "unsupported": False,
}


def main() -> None:
    for module, cases in _module_cases().items():
        module_dir = OUTPUT_ROOT / module
        module_dir.mkdir(parents=True, exist_ok=True)
        (module_dir / "cases.json").write_text(
            json.dumps(cases, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    (OUTPUT_ROOT / "README.md").write_text(_readme(), encoding="utf-8")


def _case(
    module: str,
    number: int,
    scenario: str,
    user_input: str,
    expected_apis: list[str],
    steps: list[dict[str, Any]],
    keys: list[str],
    required_fields: list[str],
    comparison_type: str = "key_subset",
    required_any_fields: list[list[str]] | None = None,
) -> dict[str, Any]:
    comparison = {
        "type": comparison_type,
        "keys": keys,
        "required_fields": required_fields,
    }
    if required_any_fields:
        comparison["required_any_fields"] = required_any_fields
    return {
        "id": f"{module}-XAPI-{number:03d}",
        "api": module,
        "scenario": scenario,
        "user_input": user_input,
        "expected_api": expected_apis[0],
        "expected_apis": expected_apis,
        "expected_capability": dict(CAPABILITY),
        "baseline": {"steps": steps},
        "comparison": comparison,
    }


def _step(
    step_id: str,
    url: str,
    key_fields: list[str],
    bind: dict[str, str] | list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    step = {"id": step_id, "url": url, "key_fields": key_fields}
    if isinstance(bind, list):
        step["bindings"] = bind
    elif bind:
        step["bind"] = bind
    return step


def _bind(source_step: str, source_field: str, target_field: str) -> dict[str, str]:
    return {
        "source_step": source_step,
        "source_field": source_field,
        "target_field": target_field,
    }


def _module_cases() -> dict[str, list[dict[str, Any]]]:
    return {
        "FI": _fi_cases(),
        "CO": _co_cases(),
        "SD": _sd_cases(),
        "MM": _mm_cases(),
        "PP": _pp_cases(),
    }


def _fi_cases() -> list[dict[str, Any]]:
    module = "FI"
    company = _step(
        "company",
        "/sap/opu/odata/sap/API_COMPANYCODE_SRV/A_CompanyCode?$select=CompanyCode,ChartOfAccounts,Currency,Company&$filter=CompanyCode eq '1710'&$top=5",
        ["CompanyCode"],
    )
    ycoa = _bind("company", "ChartOfAccounts", "ChartOfAccounts")
    return [
        _case(module, 1, "company_chart_accounts", "查询公司1710使用的科目表下有哪些总账科目", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,GLAccountType,IsProfitLossAccount,IsBalanceSheetAccount&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["ChartOfAccounts", "GLAccount"]),
        _case(module, 2, "company_profit_loss_accounts", "查询公司1710科目表里的损益类科目", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,GLAccountType,IsProfitLossAccount,ProfitLossAccountType&$filter=IsProfitLossAccount eq true&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["ChartOfAccounts", "GLAccount", "IsProfitLossAccount"]),
        _case(module, 3, "company_balance_sheet_accounts", "查询公司1710科目表里的资产负债类科目", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,GLAccountType,IsBalanceSheetAccount&$filter=IsBalanceSheetAccount eq true&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["ChartOfAccounts", "GLAccount", "IsBalanceSheetAccount"]),
        _case(module, 4, "company_blocked_posting_accounts", "查询公司1710科目表中被冻结过账的总账科目", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,AccountIsBlockedForPosting&$filter=AccountIsBlockedForPosting eq true&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["ChartOfAccounts", "GLAccount", "AccountIsBlockedForPosting"]),
        _case(module, 5, "company_account_texts", "查询公司1710科目表下总账科目的英文名称", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("texts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountText?$select=ChartOfAccounts,GLAccount,Language,GLAccountName&$filter=Language eq 'EN'&$top=50", ["ChartOfAccounts", "GLAccount", "Language"], ycoa)], ["ChartOfAccounts", "GLAccount", "Language"], ["ChartOfAccounts", "GLAccount", "GLAccountName"]),
        _case(module, 6, "company_journal_items", "查询公司1710的日记账行项目和对应科目金额", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,GLAccount,AmountInCompanyCodeCurrency,CompanyCodeCurrency&$top=50", ["ID"], _bind("company", "CompanyCode", "CompanyCode"))], ["ID"], ["ID", "CompanyCode", "GLAccount"]),
        _case(module, 7, "company_journal_items_for_account", "查询公司1710中科目10010000的日记账行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,GLAccount,AmountInCompanyCodeCurrency&$filter=GLAccount eq '10010000'&$top=50", ["CompanyCode", "GLAccount"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount"], ["CompanyCode", "GLAccount", "AmountInCompanyCodeCurrency"]),
        _case(module, 8, "company_gl_line_items", "查询公司1710的总账行项目清单", ["API_COMPANYCODE_SRV", "API_GLACCOUNTLINEITEM"], [company, _step("items", "/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem?$select=CompanyCode,FiscalYear,AccountingDocument,Ledger,GLAccount,AmountInCompanyCodeCurrency&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], ["CompanyCode", "AccountingDocument", "GLAccount"]),
        _case(module, 9, "company_operational_accounting_items", "查询公司1710的运营会计凭证项目", ["API_COMPANYCODE_SRV", "API_OPLACCTGDOCITEMCUBE_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_OPLACCTGDOCITEMCUBE_SRV/A_OperationalAcctgDocItemCube?$select=CompanyCode,FiscalYear,AccountingDocument,AccountingDocumentItem,GLAccount,CostCenter,ProfitCenter,AmountInCompanyCodeCurrency&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"], ["CompanyCode", "AccountingDocument", "GLAccount"]),
        _case(module, 10, "leading_ledger_company_line_items", "查询公司1710主导ledger的总账行项目", ["API_LEDGER_SRV", "API_GLACCOUNTLINEITEM"], [_step("ledgers", "/sap/opu/odata/sap/API_LEDGER_SRV/A_Ledger?$select=Ledger,IsLeadingLedger&$filter=IsLeadingLedger eq true&$top=5", ["Ledger"]), _step("items", "/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem?$select=CompanyCode,FiscalYear,AccountingDocument,Ledger,GLAccount,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710'&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], _bind("ledgers", "Ledger", "Ledger"))], ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], ["CompanyCode", "AccountingDocument", "Ledger"]),
        _case(module, 11, "ledger_names_for_company_items", "查询公司1710总账行项目使用到的ledger名称", ["API_GLACCOUNTLINEITEM", "API_LEDGER_SRV"], [_step("items", "/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem?$select=Ledger,CompanyCode&$filter=CompanyCode eq '1710'&$top=10", ["Ledger"]), _step("ledgers", "/sap/opu/odata/sap/API_LEDGER_SRV/A_Ledger?$select=Ledger,LedgerApplication,IsLeadingLedger&$top=50", ["Ledger"], _bind("items", "Ledger", "Ledger"))], ["Ledger"], ["Ledger"]),
        _case(module, 12, "company_partner_company_master", "查询公司1710对应的交易伙伴公司主数据", ["API_COMPANYCODE_SRV", "API_PARTNERCOMPANY_SRV"], [company, _step("partners", "/sap/opu/odata/sap/API_PARTNERCOMPANY_SRV/A_PartnerCompany?$select=PartnerCompany,CompanyName&$top=50", ["PartnerCompany"], _bind("company", "Company", "PartnerCompany"))], ["PartnerCompany"], ["PartnerCompany"]),
        _case(module, 13, "company_account_types", "查询公司1710科目表下各类总账科目", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,GLAccountType,GLAccountGroup&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["GLAccount"], required_any_fields=[["GLAccountType", "IsBalanceSheetAccount", "ProfitLossAccountType"]]),
        _case(module, 14, "company_sample_accounts", "查询公司1710科目表里的样本科目关系", ["API_COMPANYCODE_SRV", "API_GLACCOUNTINCHARTOFACCOUNTS_SRV"], [company, _step("accounts", "/sap/opu/odata/sap/API_GLACCOUNTINCHARTOFACCOUNTS_SRV/A_GLAccountInChartOfAccounts?$select=ChartOfAccounts,GLAccount,SampleGLAccount&$filter=SampleGLAccount ne ''&$top=50", ["ChartOfAccounts", "GLAccount"], ycoa)], ["ChartOfAccounts", "GLAccount"], ["GLAccount", "SampleGLAccount"]),
        _case(module, 15, "company_functional_area_journal_items", "查询公司1710带职能范围的财务行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,GLAccount,FunctionalArea,FunctionalAreaName&$filter=FunctionalArea ne ''&$top=50", ["CompanyCode", "GLAccount", "FunctionalArea"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "FunctionalArea"], ["CompanyCode", "GLAccount", "FunctionalArea"]),
        _case(module, 16, "company_costcenter_journal_items", "查询公司1710带成本中心的财务行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,GLAccount,CostCenter,AmountInCompanyCodeCurrency&$filter=CostCenter ne ''&$top=50", ["CompanyCode", "GLAccount", "CostCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "CostCenter"], ["CompanyCode", "GLAccount", "CostCenter"]),
        _case(module, 17, "company_profitcenter_journal_items", "查询公司1710带利润中心的财务行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,GLAccount,ProfitCenter,AmountInCompanyCodeCurrency&$filter=ProfitCenter ne ''&$top=50", ["CompanyCode", "GLAccount", "ProfitCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "ProfitCenter"], ["CompanyCode", "GLAccount", "ProfitCenter"]),
        _case(module, 18, "company_customer_journal_items", "查询公司1710带客户信息的财务行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,Customer,CustomerName,GLAccount,AmountInCompanyCodeCurrency&$filter=Customer ne ''&$top=50", ["CompanyCode", "GLAccount", "Customer"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "Customer"], ["CompanyCode", "GLAccount", "Customer"]),
        _case(module, 19, "company_plant_journal_items", "查询公司1710带工厂信息的财务行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,Plant,PlantName,GLAccount,AmountInCompanyCodeCurrency&$filter=Plant ne ''&$top=50", ["CompanyCode", "GLAccount", "Plant"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "Plant"], ["CompanyCode", "GLAccount", "Plant"]),
        _case(module, 20, "company_fiscal_period_journal_items", "查询公司1710会计期间2016.012的日记账行项目", ["API_COMPANYCODE_SRV", "API_JOURNALENTRYITEMBASIC_SRV"], [company, _step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,FiscalYearPeriod,GLAccount,AmountInCompanyCodeCurrency&$filter=FiscalYearPeriod eq '2016.012'&$top=50", ["CompanyCode", "GLAccount", "FiscalYearPeriod"], _bind("company", "CompanyCode", "CompanyCode"))], ["CompanyCode", "GLAccount", "FiscalYearPeriod"], ["CompanyCode", "GLAccount", "FiscalYearPeriod"]),
    ]


def _co_cases() -> list[dict[str, Any]]:
    module = "CO"
    company = _step("company", "/sap/opu/odata/sap/API_COMPANYCODE_SRV/A_CompanyCode?$select=CompanyCode,Company,ChartOfAccounts&$filter=CompanyCode eq '1710'&$top=5", ["CompanyCode"])
    cost_centers = _step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,ProfitCenter&$filter=CompanyCode eq '1710'&$top=20", ["ControllingArea", "CostCenter"])
    profit_assignments = _step("profit_assignments", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_PrftCtrCompanyCodeAssignment?$select=ControllingArea,ProfitCenter,CompanyCode&$filter=CompanyCode eq '1710'&$top=50", ["ControllingArea", "ProfitCenter", "CompanyCode"])
    return [
        _case(module, 1, "company_cost_centers", "查询公司1710下有哪些成本中心", ["API_COMPANYCODE_SRV", "API_COSTCENTER_SRV"], [company, _step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,ProfitCenter&$top=50", ["ControllingArea", "CostCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["ControllingArea", "CostCenter"], ["CostCenter", "CompanyCode"]),
        _case(module, 2, "cost_center_texts", "查询公司1710成本中心的英文名称", ["API_COSTCENTER_SRV"], [_step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,ProfitCenter&$filter=CompanyCode eq '1710'&$top=200", ["ControllingArea", "CostCenter"]), _step("texts", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenterText?$select=ControllingArea,CostCenter,Language,CostCenterName&$filter=Language eq 'EN'&$top=200", ["ControllingArea", "CostCenter", "Language"], _bind("cost_centers", "CostCenter", "CostCenter"))], ["ControllingArea", "CostCenter", "Language"], ["CostCenter", "CostCenterName"]),
        _case(module, 3, "cost_center_profit_centers", "查询公司1710成本中心对应的利润中心", ["API_COSTCENTER_SRV"], [_step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,ProfitCenter&$filter=CompanyCode eq '1710'&$top=50", ["ControllingArea", "CostCenter"])], ["ControllingArea", "CostCenter"], ["CostCenter", "ProfitCenter"]),
        _case(module, 4, "company_profit_center_assignments", "查询公司1710分配了哪些利润中心", ["API_COMPANYCODE_SRV", "API_PROFITCENTER_SRV"], [company, _step("assignments", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_PrftCtrCompanyCodeAssignment?$select=ControllingArea,ProfitCenter,CompanyCode&$top=50", ["ControllingArea", "ProfitCenter", "CompanyCode"], _bind("company", "CompanyCode", "CompanyCode"))], ["ControllingArea", "ProfitCenter", "CompanyCode"], ["ProfitCenter", "CompanyCode"]),
        _case(module, 5, "profit_center_texts", "查询公司1710利润中心的英文名称", ["API_PROFITCENTER_SRV"], [profit_assignments, _step("texts", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_ProfitCenterText?$select=ControllingArea,ProfitCenter,Language,ProfitCenterName&$filter=Language eq 'EN'&$top=50", ["ControllingArea", "ProfitCenter", "Language"], _bind("profit_assignments", "ProfitCenter", "ProfitCenter"))], ["ControllingArea", "ProfitCenter", "Language"], ["ProfitCenter", "ProfitCenterName"]),
        _case(module, 6, "cost_center_journal_items", "查询公司1710成本中心上的财务行项目", ["API_JOURNALENTRYITEMBASIC_SRV"], [_step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,CostCenter,GLAccount,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and CostCenter ne ''&$top=50", ["ID"])], ["ID"], ["ID", "CostCenter"]),
        _case(module, 7, "profit_center_journal_items", "查询公司1710利润中心上的财务行项目", ["API_JOURNALENTRYITEMBASIC_SRV"], [_step("items", "/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic?$select=ID,CompanyCode,ProfitCenter,GLAccount,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and ProfitCenter ne ''&$top=50", ["ID"])], ["ID"], ["ID", "ProfitCenter"]),
        _case(module, 8, "cost_center_gl_line_items", "查询公司1710成本中心相关的总账行项目", ["API_GLACCOUNTLINEITEM"], [_step("items", "/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem?$select=CompanyCode,FiscalYear,AccountingDocument,Ledger,GLAccount,CostCenter,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and CostCenter ne ''&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"])], ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], ["AccountingDocument", "CostCenter"]),
        _case(module, 9, "profit_center_gl_line_items", "查询公司1710利润中心相关的总账行项目", ["API_GLACCOUNTLINEITEM"], [_step("items", "/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem?$select=CompanyCode,FiscalYear,AccountingDocument,Ledger,GLAccount,ProfitCenter,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and ProfitCenter ne ''&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"])], ["CompanyCode", "FiscalYear", "AccountingDocument", "Ledger", "GLAccount"], ["AccountingDocument", "ProfitCenter"]),
        _case(module, 10, "cost_center_operational_items", "查询公司1710成本中心的运营会计项目", ["API_OPLACCTGDOCITEMCUBE_SRV"], [_step("items", "/sap/opu/odata/sap/API_OPLACCTGDOCITEMCUBE_SRV/A_OperationalAcctgDocItemCube?$select=CompanyCode,FiscalYear,AccountingDocument,AccountingDocumentItem,CostCenter,GLAccount,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and CostCenter ne ''&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"])], ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"], ["AccountingDocument", "CostCenter"]),
        _case(module, 11, "profit_center_operational_items", "查询公司1710利润中心的运营会计项目", ["API_OPLACCTGDOCITEMCUBE_SRV"], [_step("items", "/sap/opu/odata/sap/API_OPLACCTGDOCITEMCUBE_SRV/A_OperationalAcctgDocItemCube?$select=CompanyCode,FiscalYear,AccountingDocument,AccountingDocumentItem,ProfitCenter,GLAccount,AmountInCompanyCodeCurrency&$filter=CompanyCode eq '1710' and ProfitCenter ne ''&$top=50", ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"])], ["CompanyCode", "FiscalYear", "AccountingDocument", "AccountingDocumentItem"], ["AccountingDocument", "ProfitCenter"]),
        _case(module, 12, "blocked_primary_cost_centers", "查询公司1710禁止初级成本过账的成本中心", ["API_COSTCENTER_SRV"], [_step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,IsBlkdForPrimaryCostsPosting&$filter=CompanyCode eq '1710' and IsBlkdForPrimaryCostsPosting eq 'X'&$top=50", ["ControllingArea", "CostCenter"])], ["ControllingArea", "CostCenter"], ["CostCenter", "IsBlkdForPrimaryCostsPosting"]),
        _case(module, 13, "blocked_secondary_cost_centers", "查询公司1710禁止次级成本过账的成本中心", ["API_COSTCENTER_SRV"], [_step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,IsBlkdForSecondaryCostsPosting&$filter=CompanyCode eq '1710' and IsBlkdForSecondaryCostsPosting eq 'X'&$top=50", ["ControllingArea", "CostCenter"])], ["ControllingArea", "CostCenter"], ["CostCenter", "IsBlkdForSecondaryCostsPosting"]),
        _case(module, 14, "blocked_profit_centers", "查询公司1710被冻结的利润中心", ["API_PROFITCENTER_SRV"], [_step("profit_centers", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_ProfitCenter?$select=ControllingArea,ProfitCenter,CompanyCode,ProfitCenterIsBlocked&$filter=CompanyCode eq '1710' and ProfitCenterIsBlocked eq 'X'&$top=50", ["ControllingArea", "ProfitCenter"])], ["ControllingArea", "ProfitCenter"], ["ProfitCenter", "CompanyCode", "ProfitCenterIsBlocked"]),
        _case(module, 15, "cost_center_currency", "查询公司1710成本中心使用的货币", ["API_COSTCENTER_SRV"], [_step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,CostCenterCurrency&$filter=CompanyCode eq '1710'&$top=50", ["ControllingArea", "CostCenter"])], ["ControllingArea", "CostCenter"], ["CostCenter", "CostCenterCurrency"]),
        _case(module, 16, "responsible_cost_centers", "查询公司1710成本中心负责人信息", ["API_COMPANYCODE_SRV", "API_COSTCENTER_SRV"], [company, _step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,CostCtrResponsiblePersonName,CostCtrResponsibleUser&$top=50", ["ControllingArea", "CostCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["ControllingArea", "CostCenter"], ["CostCenter"]),
        _case(module, 17, "responsible_profit_centers", "查询公司1710利润中心负责人信息", ["API_PROFITCENTER_SRV"], [profit_assignments, _step("profit_centers", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_ProfitCenter?$select=ControllingArea,ProfitCenter,ProfitCtrResponsiblePersonName,ProfitCtrResponsibleUser&$top=50", ["ControllingArea", "ProfitCenter"], _bind("profit_assignments", "ProfitCenter", "ProfitCenter"))], ["ControllingArea", "ProfitCenter"], ["ProfitCenter"]),
        _case(module, 18, "cost_center_hierarchy", "查询公司1710成本中心的标准层级区域", ["API_COMPANYCODE_SRV", "API_COSTCENTER_SRV"], [company, _step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,CostCenterStandardHierArea&$top=50", ["ControllingArea", "CostCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["ControllingArea", "CostCenter"], ["CostCenter", "CostCenterStandardHierArea"]),
        _case(module, 19, "profit_center_hierarchy", "查询公司1710利润中心的标准层级", ["API_PROFITCENTER_SRV"], [profit_assignments, _step("profit_centers", "/sap/opu/odata/sap/API_PROFITCENTER_SRV/A_ProfitCenter?$select=ControllingArea,ProfitCenter,ProfitCenterStandardHierarchy&$top=50", ["ControllingArea", "ProfitCenter"], _bind("profit_assignments", "ProfitCenter", "ProfitCenter"))], ["ControllingArea", "ProfitCenter"], ["ProfitCenter", "ProfitCenterStandardHierarchy"]),
        _case(module, 20, "cost_center_category", "查询公司1710成本中心类别", ["API_COMPANYCODE_SRV", "API_COSTCENTER_SRV"], [company, _step("cost_centers", "/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter?$select=ControllingArea,CostCenter,CompanyCode,CostCenterCategory&$top=50", ["ControllingArea", "CostCenter"], _bind("company", "CompanyCode", "CompanyCode"))], ["ControllingArea", "CostCenter"], ["CostCenter", "CostCenterCategory"]),
    ]


def _sd_cases() -> list[dict[str, Any]]:
    module = "SD"
    customer = _step("customer", "/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_Customer?$select=Customer,CustomerName&$filter=Customer eq '17100003'&$top=5", ["Customer"])
    sales_orders = _step("sales_orders", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty,SalesOrganization,OverallDeliveryStatus,OverallOrdReltdBillgStatus&$filter=SoldToParty eq '17100003'&$top=20", ["SalesOrder"])
    deliveries = _step("deliveries", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryHeader?$select=DeliveryDocument,SoldToParty,OverallGoodsMovementStatus,OverallDelivReltdBillgStatus&$filter=SoldToParty eq '17100003'&$top=20", ["DeliveryDocument"])
    return [
        _case(module, 1, "customer_sales_orders", "查询客户17100003的销售订单", ["API_BUSINESS_PARTNER", "API_SALES_ORDER_SRV"], [customer, _step("orders", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty,SalesOrganization,SalesOrderType,CreationDate&$top=50", ["SalesOrder"], _bind("customer", "Customer", "SoldToParty"))], ["SalesOrder"], ["SalesOrder", "SoldToParty"]),
        _case(module, 2, "customer_sales_order_items", "查询客户17100003销售订单的行项目", ["API_SALES_ORDER_SRV"], [sales_orders, _step("items", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrderItem?$select=SalesOrder,SalesOrderItem,Material,RequestedQuantity,ProductionPlant&$top=50", ["SalesOrder", "SalesOrderItem"], _bind("sales_orders", "SalesOrder", "SalesOrder"))], ["SalesOrder", "SalesOrderItem"], ["SalesOrder", "SalesOrderItem", "Material"]),
        _case(module, 3, "customer_deliveries", "查询客户17100003的交货单", ["API_BUSINESS_PARTNER", "API_OUTBOUND_DELIVERY_SRV"], [customer, _step("deliveries", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryHeader?$select=DeliveryDocument,SoldToParty,DeliveryDate,OverallGoodsMovementStatus&$top=50", ["DeliveryDocument"], _bind("customer", "Customer", "SoldToParty"))], ["DeliveryDocument"], ["DeliveryDocument", "SoldToParty"]),
        _case(module, 4, "customer_billing_documents", "查询客户17100003的开票凭证", ["API_BUSINESS_PARTNER", "API_BILLING_DOCUMENT_SRV"], [customer, _step("billings", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocument?$select=BillingDocument,SoldToParty,CompanyCode,BillingDocumentDate&$top=50", ["BillingDocument"], _bind("customer", "Customer", "SoldToParty"))], ["BillingDocument"], ["BillingDocument", "SoldToParty"]),
        _case(module, 5, "sales_order_deliveries", "查询销售订单3773对应的交货单", ["API_SALES_ORDER_SRV", "API_OUTBOUND_DELIVERY_SRV"], [_step("order", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty&$filter=SalesOrder eq '3773'&$top=5", ["SalesOrder"]), _step("items", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryItem?$select=DeliveryDocument,DeliveryDocumentItem,ReferenceSDDocument,ReferenceSDDocumentItem,Material,ActualDeliveryQuantity&$top=50", ["DeliveryDocument", "DeliveryDocumentItem"], _bind("order", "SalesOrder", "ReferenceSDDocument"))], ["DeliveryDocument", "DeliveryDocumentItem"], ["DeliveryDocument", "ReferenceSDDocument"]),
        _case(module, 6, "sales_order_billings", "查询销售订单3773对应的开票凭证", ["API_SALES_ORDER_SRV", "API_BILLING_DOCUMENT_SRV"], [_step("order", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty&$filter=SalesOrder eq '3773'&$top=5", ["SalesOrder"]), _step("items", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocumentItem?$select=BillingDocument,BillingDocumentItem,SalesDocument,SalesDocumentItem,Material,BillingQuantity&$top=50", ["BillingDocument", "BillingDocumentItem"], _bind("order", "SalesOrder", "SalesDocument"))], ["BillingDocument", "BillingDocumentItem"], ["BillingDocument", "SalesDocument"]),
        _case(module, 7, "delivery_billing_items", "查询客户17100003交货单对应的开票项目", ["API_OUTBOUND_DELIVERY_SRV", "API_BILLING_DOCUMENT_SRV"], [deliveries, _step("items", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocumentItem?$select=BillingDocument,BillingDocumentItem,ReferenceSDDocument,ReferenceSDDocumentItem,Material,BillingQuantity&$top=50", ["BillingDocument", "BillingDocumentItem"], _bind("deliveries", "DeliveryDocument", "ReferenceSDDocument"))], ["BillingDocument", "BillingDocumentItem"], ["BillingDocument", "ReferenceSDDocument"]),
        _case(module, 8, "delivered_not_billed", "查询客户17100003已发货但还没开票的交货单", ["API_BUSINESS_PARTNER", "API_OUTBOUND_DELIVERY_SRV"], [customer, _step("deliveries", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryHeader?$select=DeliveryDocument,SoldToParty,OverallGoodsMovementStatus,OverallDelivReltdBillgStatus&$filter=OverallGoodsMovementStatus eq 'C' and OverallDelivReltdBillgStatus ne 'C'&$top=50", ["DeliveryDocument"], _bind("customer", "Customer", "SoldToParty"))], ["DeliveryDocument"], ["DeliveryDocument", "OverallGoodsMovementStatus", "OverallDelivReltdBillgStatus"]),
        _case(module, 9, "sales_order_product_descriptions", "查询客户17100003销售订单物料的英文描述", ["API_SALES_ORDER_SRV", "API_PRODUCT_SRV"], [sales_orders, _step("items", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrderItem?$select=SalesOrder,SalesOrderItem,Material&$top=20", ["Material"], _bind("sales_orders", "SalesOrder", "SalesOrder")), _step("texts", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductDescription?$select=Product,Language,ProductDescription&$filter=Language eq 'EN'&$top=50", ["Product", "Language"], _bind("items", "Material", "Product"))], ["Product", "Language"], ["Product", "ProductDescription"]),
        _case(module, 10, "customer_material_records", "查询客户17100003维护的客户物料信息", ["API_BUSINESS_PARTNER", "API_CUSTOMER_MATERIAL_SRV"], [customer, _step("records", "/sap/opu/odata/sap/API_CUSTOMER_MATERIAL_SRV/A_CustomerMaterial?$select=Customer,SalesOrganization,DistributionChannel,Material,MaterialByCustomer,MaterialDescriptionByCustomer&$top=50", ["Customer", "SalesOrganization", "DistributionChannel", "Material"], _bind("customer", "Customer", "Customer"))], ["Customer", "SalesOrganization", "DistributionChannel", "Material"], ["Customer", "Material"]),
        _case(module, 11, "customer_material_product_master", "查询客户17100003客户物料对应的产品主数据", ["API_CUSTOMER_MATERIAL_SRV", "API_PRODUCT_SRV"], [_step("records", "/sap/opu/odata/sap/API_CUSTOMER_MATERIAL_SRV/A_CustomerMaterial?$select=Customer,Material,MaterialByCustomer&$filter=Customer eq '17100003'&$top=20", ["Material"]), _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("records", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 12, "billing_headers_for_sales_order", "查询销售订单3773开票凭证的抬头信息", ["API_BILLING_DOCUMENT_SRV"], [_step("items", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocumentItem?$select=BillingDocument,BillingDocumentItem,SalesDocument&$filter=SalesDocument eq '3773'&$top=20", ["BillingDocument"]), _step("headers", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocument?$select=BillingDocument,SoldToParty,CompanyCode,BillingDocumentDate,OverallBillingStatus&$top=50", ["BillingDocument"], _bind("items", "BillingDocument", "BillingDocument"))], ["BillingDocument"], ["BillingDocument", "SoldToParty"]),
        _case(module, 13, "customer_open_sales_orders", "查询客户17100003未完全交货的销售订单", ["API_BUSINESS_PARTNER", "API_SALES_ORDER_SRV"], [customer, _step("orders", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty,OverallDeliveryStatus,OverallTotalDeliveryStatus&$filter=OverallTotalDeliveryStatus ne 'C'&$top=50", ["SalesOrder"], _bind("customer", "Customer", "SoldToParty"))], ["SalesOrder"], ["SalesOrder", "OverallTotalDeliveryStatus"]),
        _case(module, 14, "customer_unbilled_sales_orders", "查询客户17100003未完全开票的销售订单", ["API_BUSINESS_PARTNER", "API_SALES_ORDER_SRV"], [customer, _step("orders", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder,SoldToParty,OverallOrdReltdBillgStatus&$filter=OverallOrdReltdBillgStatus ne 'C'&$top=50", ["SalesOrder"], _bind("customer", "Customer", "SoldToParty"))], ["SalesOrder"], ["SalesOrder", "OverallOrdReltdBillgStatus"]),
        _case(module, 15, "delivery_item_products", "查询客户17100003交货单里的物料主数据", ["API_OUTBOUND_DELIVERY_SRV", "API_PRODUCT_SRV"], [_step("deliveries", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryHeader?$select=DeliveryDocument,SoldToParty&$filter=SoldToParty eq '17100003'&$top=20", ["DeliveryDocument"]), _step("items", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryItem?$select=DeliveryDocument,DeliveryDocumentItem,Material&$filter=Material ne ''&$top=20", ["Material"], _bind("deliveries", "DeliveryDocument", "DeliveryDocument")), _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("items", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 16, "billing_item_products", "查询客户17100003开票项目里的物料主数据", ["API_BILLING_DOCUMENT_SRV", "API_PRODUCT_SRV"], [_step("billings", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocument?$select=BillingDocument,SoldToParty&$filter=SoldToParty eq '17100003'&$top=20", ["BillingDocument"]), _step("items", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocumentItem?$select=BillingDocument,BillingDocumentItem,Material&$filter=Material ne ''&$top=20", ["Material"], _bind("billings", "BillingDocument", "BillingDocument")), _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("items", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 17, "customer_sales_order_partners", "查询客户17100003销售订单的伙伴信息", ["API_SALES_ORDER_SRV"], [sales_orders, _step("partners", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrderHeaderPartner?$select=SalesOrder,PartnerFunction,Customer,Supplier&$top=50", ["SalesOrder", "PartnerFunction"], _bind("sales_orders", "SalesOrder", "SalesOrder"))], ["SalesOrder", "PartnerFunction"], ["SalesOrder", "PartnerFunction"]),
        _case(module, 18, "customer_billing_partners", "查询客户17100003开票凭证的伙伴信息", ["API_BILLING_DOCUMENT_SRV"], [_step("billings", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocument?$select=BillingDocument,SoldToParty&$filter=SoldToParty eq '17100003'&$top=20", ["BillingDocument"]), _step("partners", "/sap/opu/odata/sap/API_BILLING_DOCUMENT_SRV/A_BillingDocumentPartner?$select=BillingDocument,PartnerFunction,Customer,Supplier&$top=50", ["BillingDocument", "PartnerFunction"], _bind("billings", "BillingDocument", "BillingDocument"))], ["BillingDocument", "PartnerFunction"], ["BillingDocument", "PartnerFunction"]),
        _case(module, 19, "delivery_items_for_customer", "查询客户17100003交货单行项目", ["API_OUTBOUND_DELIVERY_SRV"], [deliveries, _step("items", "/sap/opu/odata/sap/API_OUTBOUND_DELIVERY_SRV/A_OutbDeliveryItem?$select=DeliveryDocument,DeliveryDocumentItem,Material,ActualDeliveryQuantity,GoodsMovementStatus&$top=50", ["DeliveryDocument", "DeliveryDocumentItem"], _bind("deliveries", "DeliveryDocument", "DeliveryDocument"))], ["DeliveryDocument", "DeliveryDocumentItem"], ["DeliveryDocument", "DeliveryDocumentItem"]),
        _case(module, 20, "sales_order_pricing", "查询销售订单3773的价格条件", ["API_SALES_ORDER_SRV"], [_step("order", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$select=SalesOrder&$filter=SalesOrder eq '3773'&$top=5", ["SalesOrder"]), _step("pricing", "/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrderItemPrElement?$select=SalesOrder,SalesOrderItem,PricingProcedureStep,PricingProcedureCounter,ConditionType,ConditionAmount,ConditionCurrency&$top=50", ["SalesOrder", "SalesOrderItem", "PricingProcedureStep", "PricingProcedureCounter"], _bind("order", "SalesOrder", "SalesOrder"))], ["SalesOrder", "SalesOrderItem", "PricingProcedureStep", "PricingProcedureCounter"], ["SalesOrder", "ConditionType"]),
    ]


def _mm_cases() -> list[dict[str, Any]]:
    module = "MM"
    supplier = _step("supplier", "/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_Supplier?$select=Supplier,SupplierName&$filter=Supplier eq '17300003'&$top=5", ["Supplier"])
    po_supplier = _step("orders", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrder?$select=PurchaseOrder,Supplier,CompanyCode,PurchasingOrganization&$filter=Supplier eq '17300003'&$top=20", ["PurchaseOrder"])
    product = _step("product", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$filter=Product eq 'TG0011'&$top=5", ["Product"])
    return [
        _case(module, 1, "supplier_purchase_orders", "查询供应商17300003的采购订单", ["API_BUSINESS_PARTNER", "API_PURCHASEORDER_PROCESS_SRV"], [supplier, _step("orders", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrder?$select=PurchaseOrder,Supplier,CompanyCode,PurchasingOrganization&$top=50", ["PurchaseOrder"], _bind("supplier", "Supplier", "Supplier"))], ["PurchaseOrder"], ["PurchaseOrder", "Supplier"]),
        _case(module, 2, "supplier_purchase_order_items", "查询供应商17300003采购订单的行项目", ["API_PURCHASEORDER_PROCESS_SRV"], [po_supplier, _step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material,Plant,OrderQuantity&$top=50", ["PurchaseOrder", "PurchaseOrderItem"], _bind("orders", "PurchaseOrder", "PurchaseOrder"))], ["PurchaseOrder", "PurchaseOrderItem"], ["PurchaseOrder", "PurchaseOrderItem"]),
        _case(module, 3, "supplier_open_invoice_po_items", "查询供应商17300003还有未清发票的采购订单项目", ["API_PURCHASEORDER_PROCESS_SRV"], [po_supplier, _step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material,IsFinallyInvoiced&$filter=IsFinallyInvoiced eq false&$top=50", ["PurchaseOrder", "PurchaseOrderItem"], _bind("orders", "PurchaseOrder", "PurchaseOrder"))], ["PurchaseOrder", "PurchaseOrderItem"], ["PurchaseOrder", "IsFinallyInvoiced"]),
        _case(module, 4, "supplier_unreceived_po_items", "查询供应商17300003需要收货但未收货的采购订单项目", ["API_PURCHASEORDER_PROCESS_SRV"], [po_supplier, _step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material,GoodsReceiptIsExpected,IsCompletelyDelivered&$filter=GoodsReceiptIsExpected eq true and IsCompletelyDelivered eq false&$top=50", ["PurchaseOrder", "PurchaseOrderItem"], _bind("orders", "PurchaseOrder", "PurchaseOrder"))], ["PurchaseOrder", "PurchaseOrderItem"], ["PurchaseOrder", "GoodsReceiptIsExpected", "IsCompletelyDelivered"]),
        _case(module, 5, "supplier_invoices", "查询供应商17300003的供应商发票", ["API_BUSINESS_PARTNER", "API_SUPPLIERINVOICE_PROCESS_SRV"], [supplier, _step("invoices", "/sap/opu/odata/sap/API_SUPPLIERINVOICE_PROCESS_SRV/A_SupplierInvoice?$select=SupplierInvoice,FiscalYear,CompanyCode,InvoicingParty,InvoiceGrossAmount&$top=50", ["SupplierInvoice", "FiscalYear"], _bind("supplier", "Supplier", "InvoicingParty"))], ["SupplierInvoice", "FiscalYear"], ["SupplierInvoice", "InvoicingParty"]),
        _case(module, 6, "po_supplier_invoice_refs", "查询采购订单4500001513对应的供应商发票项目", ["API_PURCHASEORDER_PROCESS_SRV", "API_SUPPLIERINVOICE_PROCESS_SRV"], [_step("order", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrder?$select=PurchaseOrder,Supplier&$filter=PurchaseOrder eq '4500001513'&$top=5", ["PurchaseOrder"]), _step("items", "/sap/opu/odata/sap/API_SUPPLIERINVOICE_PROCESS_SRV/A_SuplrInvcItemPurOrdRef?$select=SupplierInvoice,FiscalYear,SupplierInvoiceItem,PurchaseOrder,PurchaseOrderItem,Plant,QuantityInPurchaseOrderUnit&$top=50", ["SupplierInvoice", "FiscalYear", "SupplierInvoiceItem"], _bind("order", "PurchaseOrder", "PurchaseOrder"))], ["SupplierInvoice", "FiscalYear", "SupplierInvoiceItem"], ["SupplierInvoice", "PurchaseOrder"]),
        _case(module, 7, "material_purchase_orders", "查询物料TG0011的采购订单项目", ["API_PRODUCT_SRV", "API_PURCHASEORDER_PROCESS_SRV"], [product, _step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material,Plant,OrderQuantity&$top=50", ["PurchaseOrder", "PurchaseOrderItem"], _bind("product", "Product", "Material"))], ["PurchaseOrder", "PurchaseOrderItem"], ["PurchaseOrder", "Material"]),
        _case(module, 8, "material_stock", "查询物料TG0011在工厂1710的库存", ["API_PRODUCT_SRV", "API_MATERIAL_STOCK_SRV"], [product, _step("stock", "/sap/opu/odata/sap/API_MATERIAL_STOCK_SRV/A_MatlStkInAcctMod?$select=Material,Plant,StorageLocation,InventoryStockType,MatlWrhsStkQtyInMatlBaseUnit&$filter=Plant eq '1710'&$top=50", ["Material", "Plant", "StorageLocation", "InventoryStockType"], _bind("product", "Product", "Material"))], ["Material", "Plant", "StorageLocation", "InventoryStockType"], ["Material", "Plant"]),
        _case(module, 9, "material_documents", "查询物料TG0011在工厂1710的物料凭证", ["API_PRODUCT_SRV", "API_MATERIAL_DOCUMENT_SRV"], [product, _step("docs", "/sap/opu/odata/sap/API_MATERIAL_DOCUMENT_SRV/A_MaterialDocumentItem?$select=MaterialDocument,MaterialDocumentYear,MaterialDocumentItem,Material,Plant,GoodsMovementType,QuantityInBaseUnit&$filter=Plant eq '1710'&$top=50", ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], _bind("product", "Product", "Material"))], ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], ["MaterialDocument", "Material"]),
        _case(module, 10, "material_purchase_requisitions", "查询物料TG0011在工厂1710的采购申请", ["API_PRODUCT_SRV", "API_PURCHASEREQ_PROCESS_SRV"], [product, _step("reqs", "/sap/opu/odata/sap/API_PURCHASEREQ_PROCESS_SRV/A_PurchaseRequisitionItem?$select=PurchaseRequisition,PurchaseRequisitionItem,Material,Plant,FixedSupplier,DeliveryDate&$filter=Plant eq '1710'&$top=50", ["PurchaseRequisition", "PurchaseRequisitionItem"], _bind("product", "Product", "Material"))], ["PurchaseRequisition", "PurchaseRequisitionItem"], ["PurchaseRequisition", "Material"]),
        _case(module, 11, "material_info_records", "查询物料TG0011的采购信息记录", ["API_PRODUCT_SRV", "API_INFORECORD_PROCESS_SRV"], [product, _step("records", "/sap/opu/odata/sap/API_INFORECORD_PROCESS_SRV/A_PurchasingInfoRecord?$select=PurchasingInfoRecord,Material,Supplier,MaterialGroup&$top=50", ["PurchasingInfoRecord"], _bind("product", "Product", "Material"))], ["PurchasingInfoRecord"], ["PurchasingInfoRecord", "Material"]),
        _case(module, 12, "info_record_suppliers", "查询物料TG0011采购信息记录中的供应商名称", ["API_INFORECORD_PROCESS_SRV", "API_BUSINESS_PARTNER"], [_step("records", "/sap/opu/odata/sap/API_INFORECORD_PROCESS_SRV/A_PurchasingInfoRecord?$select=PurchasingInfoRecord,Material,Supplier&$filter=Material eq 'TG0011'&$top=20", ["Supplier"]), _step("suppliers", "/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_Supplier?$select=Supplier,SupplierName&$top=50", ["Supplier"], _bind("records", "Supplier", "Supplier"))], ["Supplier"], ["Supplier"]),
        _case(module, 13, "purchase_req_fixed_suppliers", "查询物料TG0011采购申请里的固定供应商名称", ["API_PURCHASEREQ_PROCESS_SRV", "API_BUSINESS_PARTNER"], [_step("reqs", "/sap/opu/odata/sap/API_PURCHASEREQ_PROCESS_SRV/A_PurchaseRequisitionItem?$select=PurchaseRequisition,PurchaseRequisitionItem,Material,FixedSupplier&$filter=Material eq 'TG0011' and FixedSupplier ne ''&$top=20", ["FixedSupplier"]), _step("suppliers", "/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_Supplier?$select=Supplier,SupplierName&$top=50", ["Supplier"], _bind("reqs", "FixedSupplier", "Supplier"))], ["Supplier"], ["Supplier"]),
        _case(module, 14, "po_material_master", "查询供应商17300003采购订单物料的产品主数据", ["API_PURCHASEORDER_PROCESS_SRV", "API_PRODUCT_SRV"], [po_supplier, _step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material&$filter=Material ne ''&$top=20", ["Material"], _bind("orders", "PurchaseOrder", "PurchaseOrder")), _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("items", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 15, "po_schedule_lines", "查询供应商17300003采购订单的交货计划行", ["API_PURCHASEORDER_PROCESS_SRV"], [po_supplier, _step("schedule", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderScheduleLine?$select=PurchasingDocument,PurchasingDocumentItem,ScheduleLine,ScheduleLineDeliveryDate,ScheduleLineOrderQuantity&$top=50", ["PurchasingDocument", "PurchasingDocumentItem", "ScheduleLine"], _bind("orders", "PurchaseOrder", "PurchasingDocument"))], ["PurchasingDocument", "PurchasingDocumentItem", "ScheduleLine"], ["PurchasingDocument", "ScheduleLineDeliveryDate"]),
        _case(module, 16, "po_account_assignments", "查询供应商17300003采购订单的科目分配", ["API_PURCHASEORDER_PROCESS_SRV"], [po_supplier, _step("accounts", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurOrdAccountAssignment?$select=PurchaseOrder,PurchaseOrderItem,AccountAssignmentNumber,GLAccount,CostCenter&$top=50", ["PurchaseOrder", "PurchaseOrderItem", "AccountAssignmentNumber"], _bind("orders", "PurchaseOrder", "PurchaseOrder"))], ["PurchaseOrder", "PurchaseOrderItem", "AccountAssignmentNumber"], ["PurchaseOrder"]),
        _case(module, 17, "po_material_documents_for_material", "查询物料TG0011相关采购订单和收货物料凭证", ["API_PURCHASEORDER_PROCESS_SRV", "API_MATERIAL_DOCUMENT_SRV"], [_step("items", "/sap/opu/odata/sap/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrderItem?$select=PurchaseOrder,PurchaseOrderItem,Material&$filter=Material eq 'TG0011'&$top=20", ["PurchaseOrder"]), _step("docs", "/sap/opu/odata/sap/API_MATERIAL_DOCUMENT_SRV/A_MaterialDocumentItem?$select=MaterialDocument,MaterialDocumentYear,MaterialDocumentItem,PurchaseOrder,PurchaseOrderItem,Material,GoodsMovementType&$top=50", ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], _bind("items", "PurchaseOrder", "PurchaseOrder"))], ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], ["MaterialDocument", "PurchaseOrder"]),
        _case(module, 18, "supplier_invoice_po_refs", "查询供应商17300003发票关联的采购订单", ["API_SUPPLIERINVOICE_PROCESS_SRV", "API_PURCHASEORDER_PROCESS_SRV"], [_step("invoices", "/sap/opu/odata/sap/API_SUPPLIERINVOICE_PROCESS_SRV/A_SupplierInvoice?$select=SupplierInvoice,FiscalYear,InvoicingParty&$filter=InvoicingParty eq '17300003'&$top=20", ["SupplierInvoice"]), _step("refs", "/sap/opu/odata/sap/API_SUPPLIERINVOICE_PROCESS_SRV/A_SuplrInvcItemPurOrdRef?$select=SupplierInvoice,FiscalYear,SupplierInvoiceItem,PurchaseOrder,PurchaseOrderItem&$top=50", ["SupplierInvoice", "FiscalYear", "SupplierInvoiceItem"], _bind("invoices", "SupplierInvoice", "SupplierInvoice"))], ["SupplierInvoice", "FiscalYear", "SupplierInvoiceItem"], ["SupplierInvoice", "PurchaseOrder"]),
        _case(module, 19, "purchase_req_material_stock", "查询物料TG0011采购申请对应工厂的库存", ["API_PURCHASEREQ_PROCESS_SRV", "API_MATERIAL_STOCK_SRV"], [_step("reqs", "/sap/opu/odata/sap/API_PURCHASEREQ_PROCESS_SRV/A_PurchaseRequisitionItem?$select=PurchaseRequisition,PurchaseRequisitionItem,Material,Plant&$filter=Material eq 'TG0011' and Plant eq '1710'&$top=20", ["Material"]), _step("stock", "/sap/opu/odata/sap/API_MATERIAL_STOCK_SRV/A_MatlStkInAcctMod?$select=Material,Plant,StorageLocation,InventoryStockType,MatlWrhsStkQtyInMatlBaseUnit&$filter=Plant eq '1710'&$top=50", ["Material", "Plant", "StorageLocation", "InventoryStockType"], _bind("reqs", "Material", "Material"))], ["Material", "Plant", "StorageLocation", "InventoryStockType"], ["Material", "Plant"]),
        _case(module, 20, "material_goods_receipts", "查询物料TG0011在工厂1710的101收货记录", ["API_PRODUCT_SRV", "API_MATERIAL_DOCUMENT_SRV"], [product, _step("docs", "/sap/opu/odata/sap/API_MATERIAL_DOCUMENT_SRV/A_MaterialDocumentItem?$select=MaterialDocument,MaterialDocumentYear,MaterialDocumentItem,Material,Plant,GoodsMovementType,QuantityInBaseUnit&$filter=Plant eq '1710' and GoodsMovementType eq '101'&$top=50", ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], _bind("product", "Product", "Material"))], ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], ["MaterialDocument", "GoodsMovementType"]),
    ]


def _pp_cases() -> list[dict[str, Any]]:
    module = "PP"
    product = _step("product", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$filter=Product eq 'MZ-FG-R300'&$top=5", ["Product"])
    prod_orders = _step("orders", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrder_2?$select=ManufacturingOrder,Material,ProductionPlant,ManufacturingOrderType&$filter=ProductionPlant eq '1710'&$top=20", ["ManufacturingOrder"])
    planned_orders = _step("planned_orders", "/sap/opu/odata/sap/API_PLANNED_ORDERS/A_PlannedOrder?$select=PlannedOrder,Material,MRPPlant,MRPController&$filter=MRPPlant eq '1710'&$top=20", ["PlannedOrder"])
    return [
        _case(module, 1, "plant_production_orders", "查询工厂1710的生产订单", ["API_PRODUCTION_ORDER_2_SRV"], [prod_orders], ["ManufacturingOrder"], ["ManufacturingOrder", "ProductionPlant"]),
        _case(module, 2, "production_order_components", "查询工厂1710生产订单的组件", ["API_PRODUCTION_ORDER_2_SRV"], [prod_orders, _step("components", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderComponent_2?$select=ManufacturingOrder,Reservation,ReservationItem,Material,Plant,RequiredQuantity&$top=50", ["Reservation", "ReservationItem"], _bind("orders", "ManufacturingOrder", "ManufacturingOrder"))], ["Reservation", "ReservationItem"], ["ManufacturingOrder", "Material"]),
        _case(module, 3, "production_order_operations", "查询工厂1710生产订单的工序", ["API_PRODUCTION_ORDER_2_SRV"], [prod_orders, _step("operations", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderOperation_2?$select=ManufacturingOrder,ManufacturingOrderOperation,ProductionPlant,WorkCenter&$top=50", ["ManufacturingOrder", "ManufacturingOrderOperation"], _bind("orders", "ManufacturingOrder", "ManufacturingOrder"))], ["ManufacturingOrder", "ManufacturingOrderOperation"], ["ManufacturingOrder", "WorkCenter"]),
        _case(module, 4, "production_order_product_master", "查询工厂1710生产订单成品的产品主数据", ["API_PRODUCTION_ORDER_2_SRV", "API_PRODUCT_SRV"], [prod_orders, _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("orders", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 5, "production_component_stock", "查询工厂1710生产订单组件的库存", ["API_PRODUCTION_ORDER_2_SRV", "API_MATERIAL_STOCK_SRV"], [_step("components", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderComponent_2?$select=ManufacturingOrder,Material,Plant&$filter=Plant eq '1710'&$top=200", ["Material"]), _step("stock", "/sap/opu/odata/sap/API_MATERIAL_STOCK_SRV/A_MatlStkInAcctMod?$select=Material,Plant,StorageLocation,InventoryStockType,MatlWrhsStkQtyInMatlBaseUnit&$filter=Plant eq '1710'&$top=50", ["Material", "Plant", "StorageLocation", "InventoryStockType"], _bind("components", "Material", "Material"))], ["Material", "Plant", "StorageLocation", "InventoryStockType"], ["Material", "Plant"]),
        _case(module, 6, "planned_orders", "查询工厂1710的计划订单", ["API_PLANNED_ORDERS"], [planned_orders], ["PlannedOrder"], ["PlannedOrder", "MRPPlant"]),
        _case(module, 7, "planned_order_components", "查询工厂1710计划订单的组件", ["API_PLANNED_ORDERS"], [planned_orders, _step("components", "/sap/opu/odata/sap/API_PLANNED_ORDERS/A_PlannedOrderComponent?$select=PlannedOrder,Material,Plant,BillOfMaterialItemNumber,GoodsMovementEntryQty&$top=50", ["PlannedOrder", "Material"], _bind("planned_orders", "PlannedOrder", "PlannedOrder"))], ["PlannedOrder", "Material"], ["PlannedOrder", "Material"]),
        _case(module, 8, "planned_order_capacity", "查询工厂1710计划订单的产能需求", ["API_PLANNED_ORDERS"], [planned_orders, _step("capacity", "/sap/opu/odata/sap/API_PLANNED_ORDERS/A_PlannedOrderCapacity?$select=PlannedOrder,CapacityRequirement,CapacityRequirementItem,WorkCenter,OperationEarliestStartDate&$top=50", ["PlannedOrder", "CapacityRequirement", "CapacityRequirementItem"], _bind("planned_orders", "PlannedOrder", "PlannedOrder"))], ["PlannedOrder", "CapacityRequirement", "CapacityRequirementItem"], ["PlannedOrder"]),
        _case(module, 9, "mrp_materials", "查询工厂1710的MRP物料", ["API_MRP_MATERIALS_SRV_01"], [_step("mrp", "/sap/opu/odata/sap/API_MRP_MATERIALS_SRV_01/A_MRPMaterial?$select=Material,MRPPlant,MRPArea,MRPController,MRPType&$filter=MRPPlant eq '1710'&$top=50", ["Material", "MRPPlant", "MRPArea"])], ["Material", "MRPPlant", "MRPArea"], ["Material", "MRPPlant"]),
        _case(module, 10, "mrp_supply_demand", "查询物料TG0011在工厂1710的MRP供需项目", ["API_MRP_MATERIALS_SRV_01"], [_step("mrp", "/sap/opu/odata/sap/API_MRP_MATERIALS_SRV_01/A_MRPMaterial?$select=Material,MRPPlant,MRPArea&$filter=Material eq 'TG0011' and MRPPlant eq '1710'&$top=5", ["Material", "MRPPlant", "MRPArea"]), _step("items", "/sap/opu/odata/sap/API_MRP_MATERIALS_SRV_01/SupplyDemandItems?$select=Material,MRPPlant,MRPArea,MRPElement,MRPElementItem,MRPElementCategory,MRPAvailableQuantity&$filter=MRPPlant eq '1710'&$top=50", ["Material", "MRPPlant", "MRPArea", "MRPElement", "MRPElementItem"], _bind("mrp", "Material", "Material"))], ["Material", "MRPPlant", "MRPArea", "MRPElement", "MRPElementItem"], ["Material", "MRPElement"]),
        _case(module, 11, "product_routing", "查询产品MZ-FG-R300在工厂1710的生产工艺路线", ["API_PRODUCT_SRV", "API_PRODUCTION_ROUTING"], [product, _step("routings", "/sap/opu/odata/sap/API_PRODUCTION_ROUTING/ProductionRoutingMatlAssgmt?$select=Product,Plant,ProductionRouting,ProductionRoutingGroup&$filter=Plant eq '1710'&$top=50", ["Product", "Plant", "ProductionRouting", "ProductionRoutingGroup"], _bind("product", "Product", "Product"))], ["Product", "Plant", "ProductionRouting", "ProductionRoutingGroup"], ["Product", "ProductionRouting"]),
        _case(module, 12, "routing_operations", "查询产品MZ-FG-R300工艺路线的工序", ["API_PRODUCTION_ROUTING"], [_step("routings", "/sap/opu/odata/sap/API_PRODUCTION_ROUTING/ProductionRoutingMatlAssgmt?$select=Product,Plant,ProductionRouting,ProductionRoutingGroup&$filter=Product eq 'MZ-FG-R300' and Plant eq '1710'&$top=20", ["ProductionRouting", "ProductionRoutingGroup"]), _step("operations", "/sap/opu/odata/sap/API_PRODUCTION_ROUTING/ProductionRoutingOperation?$select=ProductionRouting,ProductionRoutingGroup,ProductionRoutingSequence,ProductionRoutingOpIntID,Operation,OperationText,WorkCenterInternalID&$top=50", ["ProductionRouting", "ProductionRoutingGroup", "ProductionRoutingSequence", "ProductionRoutingOpIntID"], [_bind("routings", "ProductionRouting", "ProductionRouting"), _bind("routings", "ProductionRoutingGroup", "ProductionRoutingGroup")])], ["ProductionRouting", "ProductionRoutingGroup", "ProductionRoutingSequence", "ProductionRoutingOpIntID"], ["ProductionRouting", "Operation"]),
        _case(module, 13, "routing_work_centers", "查询产品MZ-FG-R300工艺路线用到的工作中心", ["API_PRODUCTION_ROUTING", "API_WORK_CENTERS"], [_step("routings", "/sap/opu/odata/sap/API_PRODUCTION_ROUTING/ProductionRoutingMatlAssgmt?$select=Product,Plant,ProductionRouting,ProductionRoutingGroup&$filter=Product eq 'MZ-FG-R300'&$top=20", ["Product", "Plant", "ProductionRouting", "ProductionRoutingGroup"]), _step("operations", "/sap/opu/odata/sap/API_PRODUCTION_ROUTING/ProductionRoutingOperation?$select=ProductionRouting,ProductionRoutingGroup,ProductionRoutingSequence,ProductionRoutingOpIntID,Operation,WorkCenterInternalID&$top=50", ["WorkCenterInternalID"], [_bind("routings", "ProductionRouting", "ProductionRouting"), _bind("routings", "ProductionRoutingGroup", "ProductionRoutingGroup")]), _step("work_centers", "/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterAllCapacity?$select=WorkCenterInternalID,WorkCenter,Plant,WorkCenterDesc&$top=50", ["WorkCenterInternalID"], [_bind("operations", "WorkCenterInternalID", "WorkCenterInternalID"), _bind("routings", "Plant", "Plant")])], ["WorkCenterInternalID"], ["WorkCenterInternalID", "WorkCenter"]),
        _case(module, 14, "plant_work_centers", "查询工厂1710的工作中心", ["API_WORK_CENTERS"], [_step("work_centers", "/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterAllCapacity?$select=WorkCenterInternalID,WorkCenter,Plant,WorkCenterDesc&$filter=Plant eq '1710'&$top=50", ["WorkCenterInternalID"])], ["WorkCenterInternalID"], ["WorkCenter", "Plant"]),
        _case(module, 15, "work_center_operations", "查询工厂1710工作中心上的生产订单工序", ["API_PRODUCTION_ORDER_2_SRV"], [_step("operations", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderOperation_2?$select=ManufacturingOrder,ManufacturingOrderOperation,ProductionPlant,WorkCenter,MfgOrderOperationText&$filter=ProductionPlant eq '1710'&$top=50", ["ManufacturingOrder", "ManufacturingOrderOperation"])], ["ManufacturingOrder", "ManufacturingOrderOperation"], ["ManufacturingOrder", "WorkCenter"]),
        _case(module, 16, "production_order_status", "查询工厂1710生产订单的状态", ["API_PRODUCTION_ORDER_2_SRV"], [prod_orders, _step("status", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderStatus_2?$select=ManufacturingOrder,StatusCode,StatusName,StatusShortName&$top=50", ["ManufacturingOrder", "StatusCode"], _bind("orders", "ManufacturingOrder", "ManufacturingOrder"))], ["ManufacturingOrder", "StatusCode"], ["ManufacturingOrder", "StatusCode"]),
        _case(module, 17, "production_order_material_documents", "查询工厂1710生产订单对应的物料凭证", ["API_PRODUCTION_ORDER_2_SRV", "API_MATERIAL_DOCUMENT_SRV"], [_step("orders", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrder_2?$select=ManufacturingOrder,Material,ProductionPlant,ManufacturingOrderType&$filter=ProductionPlant eq '1710'&$top=200", ["ManufacturingOrder"]), _step("docs", "/sap/opu/odata/sap/API_MATERIAL_DOCUMENT_SRV/A_MaterialDocumentItem?$select=MaterialDocument,MaterialDocumentYear,MaterialDocumentItem,ManufacturingOrder,Material,Plant,GoodsMovementType&$filter=Plant eq '1710'&$top=50", ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], _bind("orders", "ManufacturingOrder", "ManufacturingOrder"))], ["MaterialDocument", "MaterialDocumentYear", "MaterialDocumentItem"], ["MaterialDocument", "ManufacturingOrder"]),
        _case(module, 18, "planned_order_product_master", "查询工厂1710计划订单物料的产品主数据", ["API_PLANNED_ORDERS", "API_PRODUCT_SRV"], [planned_orders, _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("planned_orders", "Material", "Product"))], ["Product"], ["Product"]),
        _case(module, 19, "mrp_material_stock", "查询工厂1710 MRP物料的库存", ["API_MRP_MATERIALS_SRV_01", "API_MATERIAL_STOCK_SRV"], [_step("mrp", "/sap/opu/odata/sap/API_MRP_MATERIALS_SRV_01/A_MRPMaterial?$select=Material,MRPPlant,MRPArea&$filter=MRPPlant eq '1710'&$top=20", ["Material"]), _step("stock", "/sap/opu/odata/sap/API_MATERIAL_STOCK_SRV/A_MatlStkInAcctMod?$select=Material,Plant,StorageLocation,InventoryStockType,MatlWrhsStkQtyInMatlBaseUnit&$filter=Plant eq '1710'&$top=50", ["Material", "Plant", "StorageLocation", "InventoryStockType"], _bind("mrp", "Material", "Material"))], ["Material", "Plant", "StorageLocation", "InventoryStockType"], ["Material", "Plant"]),
        _case(module, 20, "production_order_component_product_master", "查询工厂1710生产订单组件的产品主数据", ["API_PRODUCTION_ORDER_2_SRV", "API_PRODUCT_SRV"], [_step("components", "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV/A_ProductionOrderComponent_2?$select=ManufacturingOrder,Material,Plant&$filter=Plant eq '1710'&$top=200", ["Material"]), _step("products", "/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product?$select=Product,ProductType,ProductGroup&$top=50", ["Product"], _bind("components", "Material", "Product"))], ["Product"], ["Product"]),
    ]


def _readme() -> str:
    return """# Cross-API Natural Language E2E Test Assets

This folder stores module-oriented cross-API test scenarios for FI, CO, SD, MM, and PP.

Each module has 20 business-language cases. A case contains deterministic SAP OData baseline
steps and an LLM-first frontend-chain question. Baselines are captured under
`{MODULE}/baselines/`; run outputs are stored separately under `data/cross_api_test_runs`.

Rules:

- User inputs must use normal business wording and avoid API/entity/field names.
- Different parameter values do not count as different scenarios.
- Cross-API intent is declared with `expected_apis`.
- General fixes should stay in shared routing/planning/schema logic.
- API-specific business knowledge should be captured in that API's `skill.md`.
"""


if __name__ == "__main__":
    main()
